server:
  port: 8080

spring:
  application:
    name: petzzang-service

  #DB INFO
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: pzadmin!
    url: jdbc:mysql://pz-db.0e26ef89.cbfb40eb783145cbbc2fec56fd713fd3.mysql.managed-service.kr-central-1.kakaokic.com:3306/petzzangdb?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&autoReconnect=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true


  # profiles:
  #   active: dev

  #JPA/Hibernate
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        show-sql: true
    show-sql: 'true'

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: DEBUG

management:
  health:
    solr:
      enabled: false